NANOSECONDS = 1
MICROSECONDS = NANOSECONDS * 1000
MILLISECONDS = MICROSECONDS * 1000
SECONDS = MILLISECONDS * 1000

MINE_RATE = 4 * SECONDS

STARTING_BALANCE = 1000

MINING_REWARD = 50
MINING_REWARD_INPUT = {'address': '*--official-mining-reward--*'}
